baseURL = 'https://esmoore.com/'
languageCode = 'en-us'
title = 'Eric S. Moore'

ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.extensions]
typographer = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]